_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
