_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
clip_model:
    value: hf-hub:laion/CLIP-ViT-L-14-laion2B-s32B-b82K
dataset:
    value: imagenet_sketch
wandb_project:
    value: clip-finetuning
